[package]
name = "ember"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ember_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13.5", default-features = false, features = ["blocking", "rustls"] }
sha2 = "0.10.9"
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }
tauri = { version = "2", features = ["tray-icon"] }
zip = { version = "7.2.0", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
sequoia-openpgp = { version = "2.4.1", default-features = false, features = ["crypto-cng"] }
windows-sys = { version = "0.61.2", features = [
  "Win32_System_Power",
  "Win32_System_JobObjects",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
  "Win32_System_Pipes",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_UI_Input_KeyboardAndMouse",
] }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
